module.exports = [
  // core
  'react',
  'redux',
  'react-dom',
  'react-redux',
  'redux-thunk',
  'react-router',
  'redux-actions',
  'redux-persist',
  'react-router-dom',
  'react-transition-group/CSSTransitionGroup',
  // plugins
  'qs',
  'md5',
  'nprogress',
  'antd/lib/button',
  'antd/lib/checkbox',
  'antd/lib/col',
  'antd/lib/date-picker',
  'antd/lib/form',
  'antd/lib/icon',
  'antd/lib/input',
  'antd/lib/message',
  'antd/lib/modal',
  'antd/lib/notification',
  'antd/lib/radio',
  'antd/lib/row',
  'antd/lib/select',
  'antd/lib/slider',
  'antd/lib/spin',
  'antd/lib/table',
  'antd/lib/tree',
  'antd/lib/tree-select',
  'antd/lib/popconfirm'
]